name: "unit-tests"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build-ystdlib-cpp:
    strategy:
      matrix:
        os:
          - "macos-14"
          - "macos-15"
          - "ubuntu-22.04"
          - "ubuntu-24.04"
    runs-on: "${{matrix.os}}"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli"

      - if: "matrix.os == 'macos-14'"
        name: "Install MacOS-14 deps: coreutils (for md5sum) and AppleClang16 (for c++20)"
        run: |-
          brew install coreutils
          brew install llvm@16

      - name: "Run unit tests"
        env:
          CC: >-
            ${{ if eq(matrix.os, "macos-14") }} ? "/opt/homebrew/opt/llvm@16/bin/clang" : ""
          CXX: >-
            ${{ if eq(matrix.os, "macos-14") }} ? "/opt/homebrew/opt/llvm@16/bin/clang++" : ""
        run: |-
          task clean
          task test-all
